// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package elasticsearch_domain

import (
	"context"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/elasticsearchservice"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/elasticsearchservice-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.ElasticsearchService{}
	_ = &svcapitypes.ElasticsearchDomain{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.DescribeElasticsearchDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeElasticsearchDomain", respErr)
	if respErr != nil {
		if awsErr, ok := ackerr.AWSError(respErr); ok && awsErr.Code() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, respErr
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DomainStatus.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DomainStatus.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DomainStatus.AccessPolicies != nil {
		ko.Spec.AccessPolicies = resp.DomainStatus.AccessPolicies
	}
	if resp.DomainStatus.AdvancedOptions != nil {
		f2 := map[string]*string{}
		for f2key, f2valiter := range resp.DomainStatus.AdvancedOptions {
			var f2val string
			f2val = *f2valiter
			f2[f2key] = &f2val
		}
		ko.Spec.AdvancedOptions = f2
	}
	if resp.DomainStatus.AdvancedSecurityOptions != nil {
		f3 := &svcapitypes.AdvancedSecurityOptionsInput{}
		if resp.DomainStatus.AdvancedSecurityOptions.Enabled != nil {
			f3.Enabled = resp.DomainStatus.AdvancedSecurityOptions.Enabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled != nil {
			f3.InternalUserDatabaseEnabled = resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions != nil {
			f3f2 := &svcapitypes.SAMLOptionsInput{}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled != nil {
				f3f2.Enabled = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp != nil {
				f3f2f1 := &svcapitypes.SAMLIDp{}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId != nil {
					f3f2f1.EntityID = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId
				}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent != nil {
					f3f2f1.MetadataContent = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent
				}
				f3f2.IDp = f3f2f1
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey != nil {
				f3f2.RolesKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes != nil {
				f3f2.SessionTimeoutMinutes = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey != nil {
				f3f2.SubjectKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey
			}
			f3.SAMLOptions = f3f2
		}
		ko.Spec.AdvancedSecurityOptions = f3
	}
	if resp.DomainStatus.CognitoOptions != nil {
		f4 := &svcapitypes.CognitoOptions{}
		if resp.DomainStatus.CognitoOptions.Enabled != nil {
			f4.Enabled = resp.DomainStatus.CognitoOptions.Enabled
		}
		if resp.DomainStatus.CognitoOptions.IdentityPoolId != nil {
			f4.IDentityPoolID = resp.DomainStatus.CognitoOptions.IdentityPoolId
		}
		if resp.DomainStatus.CognitoOptions.RoleArn != nil {
			f4.RoleARN = resp.DomainStatus.CognitoOptions.RoleArn
		}
		if resp.DomainStatus.CognitoOptions.UserPoolId != nil {
			f4.UserPoolID = resp.DomainStatus.CognitoOptions.UserPoolId
		}
		ko.Spec.CognitoOptions = f4
	}
	if resp.DomainStatus.Created != nil {
		ko.Status.Created = resp.DomainStatus.Created
	}
	if resp.DomainStatus.Deleted != nil {
		ko.Status.Deleted = resp.DomainStatus.Deleted
	}
	if resp.DomainStatus.DomainEndpointOptions != nil {
		f7 := &svcapitypes.DomainEndpointOptions{}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpoint != nil {
			f7.CustomEndpoint = resp.DomainStatus.DomainEndpointOptions.CustomEndpoint
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn != nil {
			f7.CustomEndpointCertificateARN = resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled != nil {
			f7.CustomEndpointEnabled = resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled
		}
		if resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS != nil {
			f7.EnforceHTTPS = resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS
		}
		if resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy != nil {
			f7.TLSSecurityPolicy = resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy
		}
		ko.Spec.DomainEndpointOptions = f7
	}
	if resp.DomainStatus.DomainId != nil {
		ko.Status.DomainID = resp.DomainStatus.DomainId
	}
	if resp.DomainStatus.DomainName != nil {
		ko.Spec.DomainName = resp.DomainStatus.DomainName
	}
	if resp.DomainStatus.EBSOptions != nil {
		f10 := &svcapitypes.EBSOptions{}
		if resp.DomainStatus.EBSOptions.EBSEnabled != nil {
			f10.EBSEnabled = resp.DomainStatus.EBSOptions.EBSEnabled
		}
		if resp.DomainStatus.EBSOptions.Iops != nil {
			f10.IOPS = resp.DomainStatus.EBSOptions.Iops
		}
		if resp.DomainStatus.EBSOptions.VolumeSize != nil {
			f10.VolumeSize = resp.DomainStatus.EBSOptions.VolumeSize
		}
		if resp.DomainStatus.EBSOptions.VolumeType != nil {
			f10.VolumeType = resp.DomainStatus.EBSOptions.VolumeType
		}
		ko.Spec.EBSOptions = f10
	}
	if resp.DomainStatus.ElasticsearchClusterConfig != nil {
		f11 := &svcapitypes.ElasticsearchClusterConfig{}
		if resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterCount != nil {
			f11.DedicatedMasterCount = resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterCount
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterEnabled != nil {
			f11.DedicatedMasterEnabled = resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterEnabled
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterType != nil {
			f11.DedicatedMasterType = resp.DomainStatus.ElasticsearchClusterConfig.DedicatedMasterType
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.InstanceCount != nil {
			f11.InstanceCount = resp.DomainStatus.ElasticsearchClusterConfig.InstanceCount
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.InstanceType != nil {
			f11.InstanceType = resp.DomainStatus.ElasticsearchClusterConfig.InstanceType
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.WarmCount != nil {
			f11.WarmCount = resp.DomainStatus.ElasticsearchClusterConfig.WarmCount
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.WarmEnabled != nil {
			f11.WarmEnabled = resp.DomainStatus.ElasticsearchClusterConfig.WarmEnabled
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.WarmType != nil {
			f11.WarmType = resp.DomainStatus.ElasticsearchClusterConfig.WarmType
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessConfig != nil {
			f11f8 := &svcapitypes.ZoneAwarenessConfig{}
			if resp.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount != nil {
				f11f8.AvailabilityZoneCount = resp.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount
			}
			f11.ZoneAwarenessConfig = f11f8
		}
		if resp.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessEnabled != nil {
			f11.ZoneAwarenessEnabled = resp.DomainStatus.ElasticsearchClusterConfig.ZoneAwarenessEnabled
		}
		ko.Spec.ElasticsearchClusterConfig = f11
	}
	if resp.DomainStatus.ElasticsearchVersion != nil {
		ko.Spec.ElasticsearchVersion = resp.DomainStatus.ElasticsearchVersion
	}
	if resp.DomainStatus.EncryptionAtRestOptions != nil {
		f13 := &svcapitypes.EncryptionAtRestOptions{}
		if resp.DomainStatus.EncryptionAtRestOptions.Enabled != nil {
			f13.Enabled = resp.DomainStatus.EncryptionAtRestOptions.Enabled
		}
		if resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId != nil {
			f13.KMSKeyID = resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId
		}
		ko.Spec.EncryptionAtRestOptions = f13
	}
	if resp.DomainStatus.Endpoint != nil {
		ko.Status.Endpoint = resp.DomainStatus.Endpoint
	}
	if resp.DomainStatus.Endpoints != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.DomainStatus.Endpoints {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Status.Endpoints = f15
	}
	if resp.DomainStatus.LogPublishingOptions != nil {
		f16 := map[string]*svcapitypes.LogPublishingOption{}
		for f16key, f16valiter := range resp.DomainStatus.LogPublishingOptions {
			f16val := &svcapitypes.LogPublishingOption{}
			if f16valiter.CloudWatchLogsLogGroupArn != nil {
				f16val.CloudWatchLogsLogGroupARN = f16valiter.CloudWatchLogsLogGroupArn
			}
			if f16valiter.Enabled != nil {
				f16val.Enabled = f16valiter.Enabled
			}
			f16[f16key] = f16val
		}
		ko.Spec.LogPublishingOptions = f16
	}
	if resp.DomainStatus.NodeToNodeEncryptionOptions != nil {
		f17 := &svcapitypes.NodeToNodeEncryptionOptions{}
		if resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled != nil {
			f17.Enabled = resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled
		}
		ko.Spec.NodeToNodeEncryptionOptions = f17
	}
	if resp.DomainStatus.Processing != nil {
		ko.Status.Processing = resp.DomainStatus.Processing
	}
	if resp.DomainStatus.ServiceSoftwareOptions != nil {
		f19 := &svcapitypes.ServiceSoftwareOptions{}
		if resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate != nil {
			f19.AutomatedUpdateDate = &metav1.Time{*resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate}
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Cancellable != nil {
			f19.Cancellable = resp.DomainStatus.ServiceSoftwareOptions.Cancellable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion != nil {
			f19.CurrentVersion = resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Description != nil {
			f19.Description = resp.DomainStatus.ServiceSoftwareOptions.Description
		}
		if resp.DomainStatus.ServiceSoftwareOptions.NewVersion != nil {
			f19.NewVersion = resp.DomainStatus.ServiceSoftwareOptions.NewVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment != nil {
			f19.OptionalDeployment = resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable != nil {
			f19.UpdateAvailable = resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus != nil {
			f19.UpdateStatus = resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus
		}
		ko.Status.ServiceSoftwareOptions = f19
	}
	if resp.DomainStatus.SnapshotOptions != nil {
		f20 := &svcapitypes.SnapshotOptions{}
		if resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour != nil {
			f20.AutomatedSnapshotStartHour = resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour
		}
		ko.Spec.SnapshotOptions = f20
	}
	if resp.DomainStatus.UpgradeProcessing != nil {
		ko.Status.UpgradeProcessing = resp.DomainStatus.UpgradeProcessing
	}
	if resp.DomainStatus.VPCOptions != nil {
		f22 := &svcapitypes.VPCOptions{}
		if resp.DomainStatus.VPCOptions.SecurityGroupIds != nil {
			f22f1 := []*string{}
			for _, f22f1iter := range resp.DomainStatus.VPCOptions.SecurityGroupIds {
				var f22f1elem string
				f22f1elem = *f22f1iter
				f22f1 = append(f22f1, &f22f1elem)
			}
			f22.SecurityGroupIDs = f22f1
		}
		if resp.DomainStatus.VPCOptions.SubnetIds != nil {
			f22f2 := []*string{}
			for _, f22f2iter := range resp.DomainStatus.VPCOptions.SubnetIds {
				var f22f2elem string
				f22f2elem = *f22f2iter
				f22f2 = append(f22f2, &f22f2elem)
			}
			f22.SubnetIDs = f22f2
		}
		ko.Spec.VPCOptions = f22
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required by not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.DomainName == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeElasticsearchDomainInput, error) {
	res := &svcsdk.DescribeElasticsearchDomainInput{}

	if r.ko.Spec.DomainName != nil {
		res.SetDomainName(*r.ko.Spec.DomainName)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a new resource with any fields in the Status field filled in
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	r *resource,
) (*resource, error) {
	input, err := rm.newCreateRequestPayload(ctx, r)
	if err != nil {
		return nil, err
	}

	resp, respErr := rm.sdkapi.CreateElasticsearchDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateElasticsearchDomain", respErr)
	if respErr != nil {
		return nil, respErr
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DomainStatus.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DomainStatus.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DomainStatus.Created != nil {
		ko.Status.Created = resp.DomainStatus.Created
	}
	if resp.DomainStatus.Deleted != nil {
		ko.Status.Deleted = resp.DomainStatus.Deleted
	}
	if resp.DomainStatus.DomainId != nil {
		ko.Status.DomainID = resp.DomainStatus.DomainId
	}
	if resp.DomainStatus.Endpoint != nil {
		ko.Status.Endpoint = resp.DomainStatus.Endpoint
	}
	if resp.DomainStatus.Endpoints != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.DomainStatus.Endpoints {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Status.Endpoints = f15
	}
	if resp.DomainStatus.Processing != nil {
		ko.Status.Processing = resp.DomainStatus.Processing
	}
	if resp.DomainStatus.ServiceSoftwareOptions != nil {
		f19 := &svcapitypes.ServiceSoftwareOptions{}
		if resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate != nil {
			f19.AutomatedUpdateDate = &metav1.Time{*resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate}
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Cancellable != nil {
			f19.Cancellable = resp.DomainStatus.ServiceSoftwareOptions.Cancellable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion != nil {
			f19.CurrentVersion = resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Description != nil {
			f19.Description = resp.DomainStatus.ServiceSoftwareOptions.Description
		}
		if resp.DomainStatus.ServiceSoftwareOptions.NewVersion != nil {
			f19.NewVersion = resp.DomainStatus.ServiceSoftwareOptions.NewVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment != nil {
			f19.OptionalDeployment = resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable != nil {
			f19.UpdateAvailable = resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus != nil {
			f19.UpdateStatus = resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus
		}
		ko.Status.ServiceSoftwareOptions = f19
	}
	if resp.DomainStatus.UpgradeProcessing != nil {
		ko.Status.UpgradeProcessing = resp.DomainStatus.UpgradeProcessing
	}

	rm.setStatusDefaults(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateElasticsearchDomainInput, error) {
	res := &svcsdk.CreateElasticsearchDomainInput{}

	if r.ko.Spec.AccessPolicies != nil {
		res.SetAccessPolicies(*r.ko.Spec.AccessPolicies)
	}
	if r.ko.Spec.AdvancedOptions != nil {
		f1 := map[string]*string{}
		for f1key, f1valiter := range r.ko.Spec.AdvancedOptions {
			var f1val string
			f1val = *f1valiter
			f1[f1key] = &f1val
		}
		res.SetAdvancedOptions(f1)
	}
	if r.ko.Spec.AdvancedSecurityOptions != nil {
		f2 := &svcsdk.AdvancedSecurityOptionsInput{}
		if r.ko.Spec.AdvancedSecurityOptions.Enabled != nil {
			f2.SetEnabled(*r.ko.Spec.AdvancedSecurityOptions.Enabled)
		}
		if r.ko.Spec.AdvancedSecurityOptions.InternalUserDatabaseEnabled != nil {
			f2.SetInternalUserDatabaseEnabled(*r.ko.Spec.AdvancedSecurityOptions.InternalUserDatabaseEnabled)
		}
		if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions != nil {
			f2f2 := &svcsdk.MasterUserOptions{}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserARN != nil {
				f2f2.SetMasterUserARN(*r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserARN)
			}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserName != nil {
				f2f2.SetMasterUserName(*r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserName)
			}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserPassword != nil {
				f2f2.SetMasterUserPassword(*r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserPassword)
			}
			f2.SetMasterUserOptions(f2f2)
		}
		if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions != nil {
			f2f3 := &svcsdk.SAMLOptionsInput{}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.Enabled != nil {
				f2f3.SetEnabled(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.Enabled)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp != nil {
				f2f3f1 := &svcsdk.SAMLIdp{}
				if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.EntityID != nil {
					f2f3f1.SetEntityId(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.EntityID)
				}
				if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.MetadataContent != nil {
					f2f3f1.SetMetadataContent(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.MetadataContent)
				}
				f2f3.SetIdp(f2f3f1)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterBackendRole != nil {
				f2f3.SetMasterBackendRole(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterBackendRole)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterUserName != nil {
				f2f3.SetMasterUserName(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterUserName)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.RolesKey != nil {
				f2f3.SetRolesKey(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.RolesKey)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes != nil {
				f2f3.SetSessionTimeoutMinutes(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SubjectKey != nil {
				f2f3.SetSubjectKey(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SubjectKey)
			}
			f2.SetSAMLOptions(f2f3)
		}
		res.SetAdvancedSecurityOptions(f2)
	}
	if r.ko.Spec.CognitoOptions != nil {
		f3 := &svcsdk.CognitoOptions{}
		if r.ko.Spec.CognitoOptions.Enabled != nil {
			f3.SetEnabled(*r.ko.Spec.CognitoOptions.Enabled)
		}
		if r.ko.Spec.CognitoOptions.IDentityPoolID != nil {
			f3.SetIdentityPoolId(*r.ko.Spec.CognitoOptions.IDentityPoolID)
		}
		if r.ko.Spec.CognitoOptions.RoleARN != nil {
			f3.SetRoleArn(*r.ko.Spec.CognitoOptions.RoleARN)
		}
		if r.ko.Spec.CognitoOptions.UserPoolID != nil {
			f3.SetUserPoolId(*r.ko.Spec.CognitoOptions.UserPoolID)
		}
		res.SetCognitoOptions(f3)
	}
	if r.ko.Spec.DomainEndpointOptions != nil {
		f4 := &svcsdk.DomainEndpointOptions{}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpoint != nil {
			f4.SetCustomEndpoint(*r.ko.Spec.DomainEndpointOptions.CustomEndpoint)
		}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpointCertificateARN != nil {
			f4.SetCustomEndpointCertificateArn(*r.ko.Spec.DomainEndpointOptions.CustomEndpointCertificateARN)
		}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpointEnabled != nil {
			f4.SetCustomEndpointEnabled(*r.ko.Spec.DomainEndpointOptions.CustomEndpointEnabled)
		}
		if r.ko.Spec.DomainEndpointOptions.EnforceHTTPS != nil {
			f4.SetEnforceHTTPS(*r.ko.Spec.DomainEndpointOptions.EnforceHTTPS)
		}
		if r.ko.Spec.DomainEndpointOptions.TLSSecurityPolicy != nil {
			f4.SetTLSSecurityPolicy(*r.ko.Spec.DomainEndpointOptions.TLSSecurityPolicy)
		}
		res.SetDomainEndpointOptions(f4)
	}
	if r.ko.Spec.DomainName != nil {
		res.SetDomainName(*r.ko.Spec.DomainName)
	}
	if r.ko.Spec.EBSOptions != nil {
		f6 := &svcsdk.EBSOptions{}
		if r.ko.Spec.EBSOptions.EBSEnabled != nil {
			f6.SetEBSEnabled(*r.ko.Spec.EBSOptions.EBSEnabled)
		}
		if r.ko.Spec.EBSOptions.IOPS != nil {
			f6.SetIops(*r.ko.Spec.EBSOptions.IOPS)
		}
		if r.ko.Spec.EBSOptions.VolumeSize != nil {
			f6.SetVolumeSize(*r.ko.Spec.EBSOptions.VolumeSize)
		}
		if r.ko.Spec.EBSOptions.VolumeType != nil {
			f6.SetVolumeType(*r.ko.Spec.EBSOptions.VolumeType)
		}
		res.SetEBSOptions(f6)
	}
	if r.ko.Spec.ElasticsearchClusterConfig != nil {
		f7 := &svcsdk.ElasticsearchClusterConfig{}
		if r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterCount != nil {
			f7.SetDedicatedMasterCount(*r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterCount)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterEnabled != nil {
			f7.SetDedicatedMasterEnabled(*r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterEnabled)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterType != nil {
			f7.SetDedicatedMasterType(*r.ko.Spec.ElasticsearchClusterConfig.DedicatedMasterType)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.InstanceCount != nil {
			f7.SetInstanceCount(*r.ko.Spec.ElasticsearchClusterConfig.InstanceCount)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.InstanceType != nil {
			f7.SetInstanceType(*r.ko.Spec.ElasticsearchClusterConfig.InstanceType)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.WarmCount != nil {
			f7.SetWarmCount(*r.ko.Spec.ElasticsearchClusterConfig.WarmCount)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.WarmEnabled != nil {
			f7.SetWarmEnabled(*r.ko.Spec.ElasticsearchClusterConfig.WarmEnabled)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.WarmType != nil {
			f7.SetWarmType(*r.ko.Spec.ElasticsearchClusterConfig.WarmType)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.ZoneAwarenessConfig != nil {
			f7f8 := &svcsdk.ZoneAwarenessConfig{}
			if r.ko.Spec.ElasticsearchClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount != nil {
				f7f8.SetAvailabilityZoneCount(*r.ko.Spec.ElasticsearchClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount)
			}
			f7.SetZoneAwarenessConfig(f7f8)
		}
		if r.ko.Spec.ElasticsearchClusterConfig.ZoneAwarenessEnabled != nil {
			f7.SetZoneAwarenessEnabled(*r.ko.Spec.ElasticsearchClusterConfig.ZoneAwarenessEnabled)
		}
		res.SetElasticsearchClusterConfig(f7)
	}
	if r.ko.Spec.ElasticsearchVersion != nil {
		res.SetElasticsearchVersion(*r.ko.Spec.ElasticsearchVersion)
	}
	if r.ko.Spec.EncryptionAtRestOptions != nil {
		f9 := &svcsdk.EncryptionAtRestOptions{}
		if r.ko.Spec.EncryptionAtRestOptions.Enabled != nil {
			f9.SetEnabled(*r.ko.Spec.EncryptionAtRestOptions.Enabled)
		}
		if r.ko.Spec.EncryptionAtRestOptions.KMSKeyID != nil {
			f9.SetKmsKeyId(*r.ko.Spec.EncryptionAtRestOptions.KMSKeyID)
		}
		res.SetEncryptionAtRestOptions(f9)
	}
	if r.ko.Spec.LogPublishingOptions != nil {
		f10 := map[string]*svcsdk.LogPublishingOption{}
		for f10key, f10valiter := range r.ko.Spec.LogPublishingOptions {
			f10val := &svcsdk.LogPublishingOption{}
			if f10valiter.CloudWatchLogsLogGroupARN != nil {
				f10val.SetCloudWatchLogsLogGroupArn(*f10valiter.CloudWatchLogsLogGroupARN)
			}
			if f10valiter.Enabled != nil {
				f10val.SetEnabled(*f10valiter.Enabled)
			}
			f10[f10key] = f10val
		}
		res.SetLogPublishingOptions(f10)
	}
	if r.ko.Spec.NodeToNodeEncryptionOptions != nil {
		f11 := &svcsdk.NodeToNodeEncryptionOptions{}
		if r.ko.Spec.NodeToNodeEncryptionOptions.Enabled != nil {
			f11.SetEnabled(*r.ko.Spec.NodeToNodeEncryptionOptions.Enabled)
		}
		res.SetNodeToNodeEncryptionOptions(f11)
	}
	if r.ko.Spec.SnapshotOptions != nil {
		f12 := &svcsdk.SnapshotOptions{}
		if r.ko.Spec.SnapshotOptions.AutomatedSnapshotStartHour != nil {
			f12.SetAutomatedSnapshotStartHour(*r.ko.Spec.SnapshotOptions.AutomatedSnapshotStartHour)
		}
		res.SetSnapshotOptions(f12)
	}
	if r.ko.Spec.VPCOptions != nil {
		f13 := &svcsdk.VPCOptions{}
		if r.ko.Spec.VPCOptions.SecurityGroupIDs != nil {
			f13f0 := []*string{}
			for _, f13f0iter := range r.ko.Spec.VPCOptions.SecurityGroupIDs {
				var f13f0elem string
				f13f0elem = *f13f0iter
				f13f0 = append(f13f0, &f13f0elem)
			}
			f13.SetSecurityGroupIds(f13f0)
		}
		if r.ko.Spec.VPCOptions.SubnetIDs != nil {
			f13f1 := []*string{}
			for _, f13f1iter := range r.ko.Spec.VPCOptions.SubnetIDs {
				var f13f1elem string
				f13f1elem = *f13f1iter
				f13f1 = append(f13f1, &f13f1elem)
			}
			f13.SetSubnetIds(f13f1)
		}
		res.SetVPCOptions(f13)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, ackerr.NotImplemented
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) error {

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return err
	}
	_, respErr := rm.sdkapi.DeleteElasticsearchDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteElasticsearchDomain", respErr)
	return respErr
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteElasticsearchDomainInput, error) {
	res := &svcsdk.DeleteElasticsearchDomainInput{}

	if r.ko.Spec.DomainName != nil {
		res.SetDomainName(*r.ko.Spec.DomainName)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ElasticsearchDomain,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
			break
		}
	}

	if rm.terminalAWSError(err) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		terminalCondition.Status = corev1.ConditionTrue
		awsErr, _ := ackerr.AWSError(err)
		errorMessage := awsErr.Message()
		terminalCondition.Message = &errorMessage
	} else if terminalCondition != nil {
		terminalCondition.Status = corev1.ConditionFalse
		terminalCondition.Message = nil
	}
	if terminalCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
